wireguard-config:
  eth: eth0
  # dir is the place where configuration files of wg are located.
  dir: /etc/wireguard/
  wgITempFile: /home/vagrant/wireguard-server/intesrface.tmpl

service-config:
  domain:
    endpoint: localhost
    port: 5353
  tls:
    enabled: false
    certFile:
    certKey:
    caFile:
    directory:
  auth:
    aKey: deneme
    sKey: test